name: Compile and test

on:
  push:
    branches:
      - '*/*'

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - run: ./mvnw clean test
