name: Compile and test

on:
  push:
    branches:
      - '*/*'
      - 'develop'

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - run: ./mvnw clean test
