name: Master Deploy

on:
  pull_request:
    branches:
      - 'master'
    types:
      - closed

env:
  ARCHIVA_USERNAME: ${{ secrets.SECRET_ARCHIVA_USERNAME }}
  ARCHIVA_PASSWORD: ${{ secrets.SECRET_ARCHIVA_PASSWORD }}

jobs:
  master-compile-test-deploy-and-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Master Compile
        run: |
          #Add maven settings.xml
          MAVEN_HOME=`./mvnw -version | grep "Maven home" | cut -d':' -f2 | sed -r "s# ##g"`
          cp ./settings.xml ${MAVEN_HOME}/conf/settings.xml

          # Add user for repository
          git config --local user.email "remi.sultan@gmail.com"
          git config --local user.name "JavaML autodeploy"
          git config push.followTags true

          # Setting the Release version to pom
          app_version=$(grep -rE "version.next=[0-9]+\.[0-9]+\.[0-9]+" version.properties | cut -d"=" -f2)
          ./set-version.sh release
          git add pom.xml pom.xml version.properties
          git commit -m "release: v-$app_version"
          git tag -a -m "$app_version" "$app_version"

          # Deploy to GCP with maven
          ./mvnw clean deploy \
            -Drelease.archiva.rsultan.username=${ARCHIVA_USERNAME} \
            -Drelease.archiva.rsultan.password=${ARCHIVA_PASSWORD}

          # Setting the next developement iteration
          ./set-version.sh snapshot
          git add pom.xml version.properties
          git commit -m "chore: jumping onto next development iteration"
      - name: Push changes made
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
